### ISSUE TITLE
Unit tests and debug tools

### ISSUE THREAD

**Issue by Zarquan** [azimuth-cloud/capi-helm-charts#232]
When these charts work, they are fine. When they don't work, the user is left in a world of hurt, rummaging round in a complex system trying to find clues as to what has gone wrong.

For a production system intended for others to use, these charts should come with a set of unit tests and debug tools that can be run on a cluster to check all the components are present and correct. 

A simple library of `kubectl` commands to look for obvious things would be a useful start. So rather than posting suggestions in a Slack channel, StackHPC can point people at a page of common debug queries they can copy and paste.

These scripts should include `kubectl` queries to resolve the random Pod names so that they will _'just work'_ without requiring the user to resolve the names manually.

These will be useful for people trying to port the Helm charts to new platforms, and for system admins trying to verify if their Openstack platform is working correctly.

**Comment by mkjpryor** [comment]
@DavidFair @meoflynn

Do you have any docs for your deployments on STFC Cloud that you could contribute to the project? Would be much appreciated.

**Comment by Zarquan** [comment]
We are trying to make a code base that is portable across all the available clouds.

Our deployment works on the Arcus Openstack system at Cambridge. It _sometimes_ works on the Somerville Openstack system at Edinburgh, but no one knows _why_.
https://github.com/lsst-uk/somerville-operations/issues/144

Several people have contributed suggestions, including a couple of people from StackHPC, but we haven't managed to identify the cause yet.

We are not experts on Openstack or ClusterAPI. We are developers trying to build our services on top of Kubernetes, so we don't have a lot of time to dedicate to debugging this. It would be really useful to have some unit tests and health diagnostics written Openstack and ClusterAPI experts that we could run on a platform to help diagnose what is going wrong.

Note - the problem is not a fault with the the capi-helm-charts themselves. The assumption is that the underlying cause lies with the configuration of the Openstack platform. The problem is that the capi-helm-charts Helm charts don't provide any feedback about what is wrong.
